language: node_js
node_js:
  - 15
warnings_are_errors: false
install:
  - yarn
before_script:
  - npm install firebase-tools -g
script:
  - yarn build:prod
  - firebase deploy --only hosting --token $FIREBASE_DEPLOY_KEY