language: node_js
node_js:
  - 'node'
warnings_are_errors: false
install:
  - yarn
script:
  - yarn build:prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 'SnHDsGfFCv0w5RCLGN3mgUuvmKgSIsLozeL+Hl1Csi2dSIP2Af46MshfgzOfIDkTFvwx6L5HHPXWa39xOocVt4VPYIXysYbhp4jpTVde/+ipgd2L8eSZ8oSZR8IyapKPdCZXckU9IMMHuABtfjH0l78aQK4yPfxT2WMz+QdHvK3gbyhBsfl9Mci5F+0xl9z0XChz5600KHqDLL0Gj2OXKmtp+IYYF+Bj1M9UMTLtu9FsLFJo3ZbJ8d6orMGWa/rYqqSfda1RogLczsIWnVHKuhoQos0/DfJOgZNUK2KiT2VMntcb+SQZUDauD5x1UDkUcOHZNF82dsMtBWRW5zKlWrIBncM6O8W50K2dtY7/y0aIU/oiUUNKKrTyWGBohWT3ByY4/6YGgUOBhl0hj/AcWpUgpn72GtMDD+jc6y/hHrdCadNY1Hcw+aIq2BFQVdu5shadWV8th8S29e+mSUqs2sRZ/W9G5XuXqEnWMOXcDH+g2eUuHHFFPvvgQuqnquyO2TDbjyYFYIlGRpzzJmb7+UHkXHOp7PjhrMOcaz86bQW9QhsQNQYQ6qxLkn1LuNuEUciTShFOfc5/S73MXgAWbyJTF5rXuoeSH3qgPt2r1HtoWlMGp8EcJe4uMc5630tx0Sxp8NH2ZT4DZC74cAvHTSSC7k/bepX/5lE5ArERJiM='
